spring.application.name=group_one
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
server.port=9090

spring.mvc.static-path-pattern=/resources/**
server.servlet.contextPath=/app

# Enable response compression
server.compression.enabled=true
server.compression.mime-types=text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
server.compression.min-response-size=1024
logging.level.org.springframework.jdbc.core=DEBUG